### ISSUE TITLE
Minecraft Bedrock Friendly Cards

### ISSUE THREAD

**Issue by QuartizOG** [kbuzsaki/bingosync#132]
I play Minecraft Bedrock on Switch with my brother locally(which is horrible) and when we revealed the card I saw "Put a banner on a Shield". I was like 'Isn't that a Java thing?' He was like 'Just ignore it.' So long story short, there should be a Bedrock Friendly Card.
![Screenshot_20210210-222314_Chrome](https://user-images.githubusercontent.com/78892255/107602292-9fa96780-6bee-11eb-9f30-e12d12fddbec.jpg)

**Comment by kbuzsaki** [comment]
I maintain the code for bingosync, but I don't write the goal lists. Different game communities will put those together and send them to me.

You can find the goal list for minecraft here: https://github.com/kbuzsaki/bingosync/blob/master/bingosync-app/generators/minecraft_randomizer_generator.js

You're welcome to create a "bedrock friendly" variant and send me that if you'd like. You can also use the custom game functionality to remove goals that you dislike without needing to go through the process of adding a new game.

I'm closing this issue because I don't think it's actionable on my end, but feel free to open a new one with a goal list that you'd like to use :)
