### ISSUE TITLE
duplicated entries

### ISSUE THREAD

**Issue by darkshoxx** [kbuzsaki/bingosync#159]
Hi,

I started a Bingo room, Myst, Non-Lockout, Seed 876525

It gave me 2 fields with the same entry.

Here's some pictures.

![2021-07-04 12_45_50-Bingosync — Mozilla Firefox](https://user-images.githubusercontent.com/43265727/124384886-493ae380-dccb-11eb-82e2-19c7122ead13.png)
![2021-07-04 13_02_52-Bingosync — Mozilla Firefox](https://user-images.githubusercontent.com/43265727/124384887-4a6c1080-dccb-11eb-9b1c-9248ba1e67c0.png)

**Comment by kbuzsaki** [comment]
It looks like the goal text "Collect Selenetic blue page" appears in the goal list twice, once at tier 15 and once again at tier 20. That's arguably a bug in the goal list, but it's not a bug in bingosync or the generator. (Though note that some generators that bingosync supports will sometimes use the same goal multiple times because they focus on per-row balance and uniqueness, not full board uniqueness).

**Comment by kbuzsaki** [comment]
You're welcome to submit a pull request that fixes the goal list, though!
