### ISSUE TITLE
New Game Request: Spyro 1 (Spyro The Dragon) - Variant 2

### ISSUE THREAD

**Issue by DrMonkeyman** [kbuzsaki/bingosync#211]
[Spyro_1_Bingo.txt](https://github.com/kbuzsaki/bingosync/files/8718225/Spyro_1_Bingo.txt)

I've noticed for a while that there is not an officially published Spyro 1 Bingo in spite of there being a 2 and 3. I created this bingo a few weeks ago and many people have used my board since in tournaments and I was wondering if it could get published since in custom board mode there's sometimes desync issues when done in custom.

**Comment by DrMonkeyman** [comment]
Nevermind someone else uploaded a Spyro 1 Bingo code so that one can just be used instead.

**Comment by kbuzsaki** [comment]
Hi, when adding another variant for a game there needs to be a descriptive name for that variant so that users can tell the difference between them.

I'm picking back up on activity for bingosync lately so I'm happy to add this new variant if you'd still like it, but given that it's been so long I'm going to close the issue.

If you'd still like it, feel free to re-open or file another issue with your requested variant name.
