### ISSUE TITLE
`/board` endpoint of a room returns status code 429

### ISSUE THREAD

**Issue by Lordmau5** [kbuzsaki/bingosync#233]
So I'm trying to write a wrapper around the rooms that would periodically fetch the newest board data from a room's `/board` endpoint in JSON and render the board myself on another page.

However, I'm getting an error with status code 429 a lot of the times when being called from a server script through e.g. NodeJS.

When I try to fetch the endpoint from a webpage it is not returning any data at all (or also runs into the error)

For some context as to why I want to work on this, it'd be because of #85 .

I've tried looking at the Bingosync server code but I'm not that knowledged in python.

An alternative, native solution would be to provide a `/board-only?pass=password_here` endpoint that would only have the board and a connection to the websocket for updates - no chat, no color selection, no col1-5 and row1-5 extra data.
Simply a spectator that joined and is observing without any additional input required.

**Comment by kbuzsaki** [comment]
The `/board` endpoint is not designed to be polled like this and is relatively expensive for the bingosync server to serve (each board square is a separate row in the database so it's doing a bunch of joins). In regular operation, the bingosync frontend javascript calls `/board` once when a game is created and then receives updates over the websocket which is much cheaper for the bingosync server to handle.

However, because `/board` is an easy API to use,. people tend to write scripts that poll it at high frequency which overloads the server. I've therefore added a rate limit in the nginx config to prevent high frequency polling. HTTP status code 429 is "Too Many Requests".

I make no promises about what the rate limit configuration will be in the future -- I might have to change it if it ends up not being sufficient -- but it's currently configured in nginx as:
```
limit_req_zone $binary_remote_addr zone=boardapi:1m rate=5r/m;
```

which should allow 5 requests per minute. In order to avoid getting throttled I recommend only making 4 requests per minute, or once every 15 seconds.

I agree that a popout page like you describe would be a good feature, but let's track that in #85, #68, or elsewhere.
