### ISSUE TITLE
Metroid Fusion randomizer bingo

### ISSUE THREAD

**Issue by lenophis** [kbuzsaki/bingosync#235]
Name: Metroid Fusion Randomizer Bingo
Short name: MFOR Bingo

Board type: SRL
Created pull request #234 which has the goals.

**Comment by kbuzsaki** [comment]
This is created, thanks for sending a pull request!

In the future please just include all of the details in the pull request rather than also filing an issue so that it's all in one place -- I checked pull requests first and missed this :)

Feel free to send another pull request if you want to update it.
