### ISSUE TITLE
New Variant for World of Warcraft

### ISSUE THREAD

**Issue by Freeng42** [kbuzsaki/bingosync#261]
Hey I think the currently existing variants are either too unbalnaced for a fair fight "using existing characters/normal variant" or feel to slow and random reggarding race choice (level 1 and random char) 
So I propose a fresh Level 10/Allied races variant: for a more balanced and race/faction indepent experience.

https://pastebin.com/948yQ2mg

Here is a first simple goal list without tiers to test out the new variant.

**Comment by kbuzsaki** [comment]
Hi there -- thanks for your interest in submitting a new goal list :)

If you're still testing out a new goal list I'd encourage you to use the "Custom (Advanced)" game type with the "Randomized" variant. That should let you get a sense of how the goal list plays before adding it to the site. World of Warcraft already has 3 different variants, so I'd like to make sure that further variants are meaningfully different and not adding confusion.

Closing this issue so that you can try out the goal list yourself first. Please feel free to file another issue when you're ready for it to be added.
