### ISSUE TITLE
Add support for variables

### ISSUE THREAD

**Issue by h3oCharles** [kbuzsaki/bingosync#287]
oh hi,

when I and a couple of other folks have thought about doing a Worms Armageddon Deathmatch Bingo board, one of the types we thought of adding is killing a specific enemy Worm with a specific weapon, or in short, "Kill X with Y", but there's no easy way to make something like this without exhausting all possible combinations

we have 3 sets of weapons (all of them can be groups of X)
the default weapons set contains 29 weapons
the team weapons set contains 8 weapons
the super weapons set contains 16 weapons

there are 22 unique enemy Worms (Y)

this would in the end create 3 fields, for example:
Kill Lambo with Mortar (default set)
Kill Spadge with Old Woman (team set)
Kill Cilla Black with Minigun (super set)

what are your thoughts?

**Comment by kbuzsaki** [comment]
This is something that you can implement with a custom generator base (see the examples here:  https://github.com/kbuzsaki/bingosync/tree/main/bingosync-app/generators/generator_bases), or by writing a program to pre-generate the goal list for you. It's not the kind of thing that I will implement myself though, since bingosync is just a platform for hosting generators :)
