### ISSUE TITLE
New Game: Freelancer

### ISSUE THREAD

**Issue by TheRealAbscond** [kbuzsaki/bingosync#306]
Hello there, I'd like to request adding [Freelancer](https://en.wikipedia.org/wiki/Freelancer_(video_game)) to the list of available games.

I'm still finalizing the goal list, but I wanted to ask something before submitting the actual list.

- For the "SRL-style goal list", does it really need to have 25 degrees of difficulty, or could it work with less?
- If above is no, then for the "simple goal list", can the goals still have types so that the generator doesn't fill the board with just goals of a single type?

Thanks for the help!

**Comment by kbuzsaki** [comment]
Yes, SRL v5 really does need exactly 25 tiers.

Currently, no, the "simple goal list" doesn't support types. Another generator has requested that so I'm looking into it.

You can comment on #338 to request this for your generator / follow along for when it's implemented :)

Closing this because there's no goal list to add. Please file another issue or reopen once you have your list.
