### ISSUE TITLE
Add Link's Awakening bingo

### ISSUE THREAD

**Issue by spicefather** [kbuzsaki/bingosync#39]
Could you please add this generator for Link's Awakening DX?

Game: The Legend of Zelda: Link's Awakening DX
Abbreviation: LADX
Generator: https://pastebin.com/jHuhVGr9

This generator is geared towards Randomizer use, as it removes some goals that are impossible for the current randomizer (i.e. goals related to ghost).

**Comment by kbuzsaki** [comment]
Whoops-- forgot to close this issue.

The Link's Awakening generator is up on the site now. I tweaked the name to match the other zeldas, which all start with "Zelda: " instead of "The Legend of Zelda", and I tweaked the short name to be "LADX Random", which matches how other randomizer variants are named.

Please let me know if you feel strongly about using a different name or shortname.
