### ISSUE TITLE
API questions

### ISSUE THREAD

**Issue by Lange** [kbuzsaki/bingosync#79]
Howdy,

@GamesDoneQuick utilizes bingosync for every bingo run in our marathons. We do this by scraping bingosync.com to log in and get a `socket_key`, then opening a connection to the websocket server to receive events in realtime for display in our stream graphics.

I'd like to make this process simpler, and eliminate the need to log in and scrape the page to get a `socket_key`. Is this something that is already possible, and that I just haven't discovered? If not, is this something that you'd be interested in supporting?

Thanks for your time,
Alex

**Comment by kbuzsaki** [comment]
So you'd like to be able to join a room and get a `socket_key` via an API endpoint? Sure, I can add that.

**Comment by Lange** [comment]
@kbuzsaki Yeah, that should cover my use case. I'm planning to author an npm package which makes it easy to consume bingosync data in either Node or the browser, and getting rid of the requirement to scrape the page to get the `socket_key` will make that much simpler. Thanks!

**Comment by kbuzsaki** [comment]
Alright, I added a couple of endpoints to support this.

Here's how you use it:
```javascript
$.ajax({
    url: "https://bingosync.com/api/join-room",
    type: "POST",
    data: JSON.stringify({
        "room": "txM6mfe6Rlih4y4UcwNdlg",
        "nickname": "fake user",
        "password": "password",
        "is_spectator": true
    }),
    success: function(response) {
        console.log("socket key is:", response["socket_key"]);
    }
});
```

The `/api/join-room` endpoint requires the `room`, `nickname`, and `password` input fields. On successful authentication, it creates a player for you and redirects you to `/api/get-socket-key/<room uuid>`, which returns a socket key for the currently logged in user. This relies on your session cookie, like the rest of the API endpoints.

Once you've joined the room for the first time, you can make a GET request to `/api/get-socket-key/<room uuid>` to get another socket key for the same player that you're currently logged in as. Please use that if you need to reconnect instead of programmatically creating a bunch of zombie players :)

**Comment by kbuzsaki** [comment]
Please re-open if there's anything else you need or you have any questions :)

**Comment by Lange** [comment]
Thanks very much! Will give this a shot soon.

**Comment by Lange** [comment]
Done, thanks for your help!

https://github.com/GamesDoneQuick/bingosync-api
